spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: @jdbc.user@
    password: @jdbc.password@
    url: @jdbc.url@
  flyway:
    baseline-on-migrate: true
    table: flyway_schema_history_streaming_app
server:
  port: 8081

application:
  sleepTime:
    beforeSend:
      amount: 30
      unit: seconds
    afterSend:
      amount: 30
      unit: seconds
  dataflows:
    -
      id: WEBDISP
      url: http://localhost:8080/api/v1/source/webdisp
      className: it.luca.streaming.factory.model.bean.webdisp.WebdispPayload
      type: xml
    -
      id: JARVIS
      url: http://localhost:8080/api/v1/source/jarvis
      className: it.luca.streaming.factory.model.bean.jarvis.JarvisPayload
      type: xml
    -
      id: INT002
      url: http://localhost:8080/api/v1/source/int002
      className: it.luca.streaming.factory.model.bean.int002.Int002Payload
      type: json
    -
      id: CONDUZIONE
      url: http://localhost:8080/api/v1/source/conduzione
      className: it.luca.streaming.factory.model.bean.conduzione.ConduzionePayload
      type: json