spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: @jdbc.user@
    password: @jdbc.password@
    url: @jdbc.url@

server:
  port: 8081

postgres:
  logTable:
    name: @jdbc.log.table@

application:
  sleepTime:
    beforeSend:
      amount: 15
      unit: seconds
    afterSend:
      amount: 15
      unit: seconds
  dataflows:
    -
      id: WEBDISP
      url: http://localhost:8080/api/v1/source/webdisp
      className: it.luca.data.model.webdisp.WebdispPayload
      type: xml
    -
      id: JARVIS
      url: http://localhost:8080/api/v1/source/jarvis
      className: it.luca.data.model.jarvis.JarvisPayload
      type: xml
    -
      id: INT002
      url: http://localhost:8080/api/v1/source/int002
      className: it.luca.data.model.int002.Int002Payload
      type: json