spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: @jdbc.user@
    password: @jdbc.password@
    url: @jdbc.url@

postgres:
  logTable:
    name: @jdbc.log.table@

application:
  sleepTimeInSeconds: 30
  dataflows:
    -
      id: WEBDISP
      url: http://localhost:8080/api/v1/webdisp
      className: it.luca.data.model.webdisp.WebdispPayload
      type: xml